//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public int aid { get; set; }
        public string FormType { get; set; }
        public int NumApprovals { get; set; }
        public string Approver1 { get; set; }
        public string Approver2 { get; set; }
        public string Approver3 { get; set; }
        public string Approver4 { get; set; }
        public string Approver5 { get; set; }
        public string Approver6 { get; set; }
        public string Approver7 { get; set; }
        public string Approver8 { get; set; }
        public string Approver9 { get; set; }
        public string Approver10 { get; set; }
        public string Copy1 { get; set; }
        public string Copy2 { get; set; }
        public string Copy3 { get; set; }
        public string Copy4 { get; set; }
        public string Copy5 { get; set; }
        public string Copy6 { get; set; }
        public string Copy7 { get; set; }
        public string Copy8 { get; set; }
        public string Copy9 { get; set; }
        public string Copy10 { get; set; }
        public string ApprovalSendTo { get; set; }
        public string FormTypeName { get; set; }
        public string Territory { get; set; }
        public string ApproverTitle1 { get; set; }
        public string ApproverTitle2 { get; set; }
        public string ApproverTitle3 { get; set; }
        public string ApproverTitle4 { get; set; }
        public string ApproverTitle5 { get; set; }
        public string ApproverTitle6 { get; set; }
        public string ApproverTitle7 { get; set; }
        public string ApproverTitle8 { get; set; }
        public string ApproverTitle9 { get; set; }
        public string ApproverTitle10 { get; set; }
        public string ApproverEmail1 { get; set; }
        public string ApproverEmail2 { get; set; }
        public string ApproverEmail3 { get; set; }
        public string ApproverEmail4 { get; set; }
        public string ApproverEmail5 { get; set; }
        public string ApproverEmail6 { get; set; }
        public string ApproverEmail7 { get; set; }
        public string ApproverEmail8 { get; set; }
        public string ApproverEmail9 { get; set; }
        public string ApproverEmail10 { get; set; }
        public string CopyEmail1 { get; set; }
        public string CopyEmail2 { get; set; }
        public string CopyEmail3 { get; set; }
        public string CopyEmail4 { get; set; }
        public string CopyEmail5 { get; set; }
        public string CopyEmail6 { get; set; }
        public string CopyEmail7 { get; set; }
        public string CopyEmail8 { get; set; }
        public string CopyEmail9 { get; set; }
        public string CopyEmail10 { get; set; }
        public string Approver0 { get; set; }
        public string ApproverTitle0 { get; set; }
        public string ApproverEmail0 { get; set; }
        public string Copy0 { get; set; }
        public string CopyEmail0 { get; set; }
        public string ApprovalSendToEmail { get; set; }
    }
}
