//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PricingDB_Entities : DbContext
    {
        public PricingDB_Entities()
            : base("name=PricingDB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FR_Form> FR_Form { get; set; }
        public virtual DbSet<Approval> Approvals { get; set; }
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<FR_Lang> FR_Lang { get; set; }
        public virtual DbSet<Lang> Langs { get; set; }
    }
}
