//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FR_Form
    {
        public int fzid { get; set; }
        public string FormType { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
        public Nullable<int> StatusNumber { get; set; }
        public string Representative { get; set; }
        public string Region { get; set; }
        public string HospitalReq { get; set; }
        public string AccountNumberReq { get; set; }
        public string CityReq { get; set; }
        public string StateReq { get; set; }
        public string ZipReq { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string SameHospAddr { get; set; }
        public string HospitalShip { get; set; }
        public string AccountNumberShip { get; set; }
        public string CityShip { get; set; }
        public string StateShip { get; set; }
        public string ZipShip { get; set; }
        public string FreezerType { get; set; }
        public string FreezerTypeOther { get; set; }
        public Nullable<System.DateTime> ReqArrivalDate { get; set; }
        public string PONumber { get; set; }
        public string Readers { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public string FormNumber { get; set; }
        public string Address1Req { get; set; }
        public string Address2Req { get; set; }
        public string Address1Ship { get; set; }
        public string Address2Ship { get; set; }
        public string CountryReq { get; set; }
        public string CountryShip { get; set; }
        public string CountryOtherReq { get; set; }
        public string CountryOtherShip { get; set; }
        public string StateOtherReq { get; set; }
        public string StateOtherShip { get; set; }
        public string Approver1 { get; set; }
        public string Approver2 { get; set; }
        public string Approver3 { get; set; }
        public string Approver4 { get; set; }
        public string Approver5 { get; set; }
        public string Approver6 { get; set; }
        public string Approver7 { get; set; }
        public string Approver8 { get; set; }
        public string Approver9 { get; set; }
        public string Approver10 { get; set; }
        public string ApproverSignature1 { get; set; }
        public string ApproverSignature2 { get; set; }
        public string ApproverSignature3 { get; set; }
        public string ApproverSignature4 { get; set; }
        public string ApproverSignature5 { get; set; }
        public string ApproverSignature6 { get; set; }
        public string ApproverSignature7 { get; set; }
        public string ApproverSignature8 { get; set; }
        public string ApproverSignature9 { get; set; }
        public string ApproverSignature10 { get; set; }
        public Nullable<System.DateTime> ApproverDate1 { get; set; }
        public Nullable<System.DateTime> ApproverDate2 { get; set; }
        public Nullable<System.DateTime> ApproverDate3 { get; set; }
        public Nullable<System.DateTime> ApproverDate4 { get; set; }
        public Nullable<System.DateTime> ApproverDate5 { get; set; }
        public Nullable<System.DateTime> ApproverDate6 { get; set; }
        public Nullable<System.DateTime> ApproverDate7 { get; set; }
        public Nullable<System.DateTime> ApproverDate8 { get; set; }
        public Nullable<System.DateTime> ApproverDate9 { get; set; }
        public Nullable<System.DateTime> ApproverDate10 { get; set; }
        public string Copy1 { get; set; }
        public string Copy2 { get; set; }
        public string Copy3 { get; set; }
        public string Copy4 { get; set; }
        public string Copy5 { get; set; }
        public string Copy6 { get; set; }
        public string Copy7 { get; set; }
        public string Copy8 { get; set; }
        public string Copy9 { get; set; }
        public string Copy10 { get; set; }
        public string ApprovalSendTo { get; set; }
        public string ApproverEmail1 { get; set; }
        public string ApproverEmail2 { get; set; }
        public string ApproverEmail3 { get; set; }
        public string ApproverEmail4 { get; set; }
        public string ApproverEmail5 { get; set; }
        public string ApproverEmail6 { get; set; }
        public string ApproverEmail7 { get; set; }
        public string ApproverEmail8 { get; set; }
        public string ApproverEmail9 { get; set; }
        public string ApproverEmail10 { get; set; }
        public string CopyEmail1 { get; set; }
        public string CopyEmail2 { get; set; }
        public string CopyEmail3 { get; set; }
        public string CopyEmail4 { get; set; }
        public string CopyEmail5 { get; set; }
        public string CopyEmail6 { get; set; }
        public string CopyEmail7 { get; set; }
        public string CopyEmail8 { get; set; }
        public string CopyEmail9 { get; set; }
        public string CopyEmail10 { get; set; }
        public string CopyEmail0 { get; set; }
        public string ApproverEmail0 { get; set; }
        public string ApprovalSendToEmail { get; set; }
        public string Copy0 { get; set; }
        public string ApproverSignature0 { get; set; }
        public Nullable<System.DateTime> ApproverDate0 { get; set; }
        public string ApproverTitle0 { get; set; }
        public string ApproverTitle1 { get; set; }
        public string ApproverTitle2 { get; set; }
        public string ApproverTitle3 { get; set; }
        public string ApproverTitle4 { get; set; }
        public string ApproverTitle5 { get; set; }
        public string ApproverTitle6 { get; set; }
        public string ApproverTitle7 { get; set; }
        public string ApproverTitle8 { get; set; }
        public string ApproverTitle9 { get; set; }
        public string ApproverTitle10 { get; set; }
        public Nullable<int> NumApprovals { get; set; }
        public string Approver0 { get; set; }
        public string ApproverDecision0 { get; set; }
        public string ApproverDecision1 { get; set; }
        public string ApproverDecision2 { get; set; }
        public string ApproverDecision3 { get; set; }
        public string ApproverDecision4 { get; set; }
        public string ApproverDecision5 { get; set; }
        public string ApproverDecision6 { get; set; }
        public string ApproverDecision7 { get; set; }
        public string ApproverDecision8 { get; set; }
        public string ApproverDecision9 { get; set; }
        public string ApproverDecision10 { get; set; }
    }
}
