//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FR_Lang
    {
        public int lfzid { get; set; }
        public string FormTitle { get; set; }
        public string FormNumber { get; set; }
        public string Created { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
        public string Representative { get; set; }
        public string Region { get; set; }
        public string SectionReqHospital { get; set; }
        public string SectionShipHospital { get; set; }
        public string SectionApprovals { get; set; }
        public string SectionDetails { get; set; }
        public string HospitalReq { get; set; }
        public string AccountNumberReq { get; set; }
        public string CityReq { get; set; }
        public string StateReq { get; set; }
        public string ZipReq { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string SameHospAddr { get; set; }
        public string HospitalShip { get; set; }
        public string AccountNumberShip { get; set; }
        public string CityShip { get; set; }
        public string StateShip { get; set; }
        public string ZipShip { get; set; }
        public string FreezerType { get; set; }
        public string FreezerTypeOther { get; set; }
        public string ReqArrivalDate { get; set; }
        public string PONumber { get; set; }
        public string Address1Req { get; set; }
        public string Address2Req { get; set; }
        public string SameAddress { get; set; }
        public string Address1Ship { get; set; }
        public string Address2Ship { get; set; }
        public string CountryReq { get; set; }
        public string CountryShip { get; set; }
        public string CountryOtherReq { get; set; }
        public string CountryOtherShip { get; set; }
        public string StateOtherReq { get; set; }
        public string StateOtherShip { get; set; }
        public string Approvers { get; set; }
        public string Signatures { get; set; }
        public string ApproverTitles { get; set; }
        public string ApproverDecisions { get; set; }
        public string LangName { get; set; }
        public string Lang { get; set; }
    }
}
