//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lang
    {
        public int lid { get; set; }
        public string Lang1 { get; set; }
        public string LangNameEnglish { get; set; }
        public string LangName { get; set; }
        public string AppTitle { get; set; }
        public string Title { get; set; }
        public string Welcome { get; set; }
        public string WelcomeMsg { get; set; }
        public string SubmitButton { get; set; }
        public string EditButton { get; set; }
        public string BackButton { get; set; }
        public string DialogMsg { get; set; }
        public string OK { get; set; }
        public string AuthMsg { get; set; }
        public string AuthErrorMsg { get; set; }
        public string AuthNoAccessMsg { get; set; }
        public string AuthOKMsg { get; set; }
        public string LoginUserName { get; set; }
        public string LoginPassword { get; set; }
        public string LoginSubmit { get; set; }
        public string NewForm { get; set; }
        public string Logout { get; set; }
        public string FormError { get; set; }
        public string AdminMenuHeader { get; set; }
        public string AdminMenuAccessControl { get; set; }
        public string AdminMenuLangSetup { get; set; }
        public string AdminLanguage { get; set; }
        public string AdminLanguageCode { get; set; }
        public string FormUpdated { get; set; }
        public string FormAdded { get; set; }
        public string UnsavedChanges { get; set; }
        public string NewLangRecord { get; set; }
        public string DeleteConfirm { get; set; }
        public string KeywordValues { get; set; }
        public string Keyword { get; set; }
        public string KeywordDescription { get; set; }
        public string KeywordValue { get; set; }
        public string AclInstructions { get; set; }
        public string AclGroups { get; set; }
        public string AclGroupsAdmin { get; set; }
        public string AclGroupsIT { get; set; }
        public string MenuFZForm { get; set; }
        public string MenuIMForm { get; set; }
        public string MenuTMForm { get; set; }
        public string MenuSAForm { get; set; }
        public string ViewCreatedBy { get; set; }
        public string ViewCreated { get; set; }
        public string ViewStatus { get; set; }
        public string ViewCompleted { get; set; }
        public string ViewFormNumber { get; set; }
        public string ViewClear { get; set; }
        public string ViewSearch { get; set; }
        public string ViewSearchFldName { get; set; }
        public string ViewSearchText { get; set; }
        public string ViewFRTitle { get; set; }
        public string ViewEnterSearchText { get; set; }
        public string AdminMenuApprSetup { get; set; }
        public string AdminMenuRegionSetup { get; set; }
        public string HospitalReq { get; set; }
        public string FreezerType { get; set; }
        public string HospitalShip { get; set; }
        public string SaveButton { get; set; }
        public string CancelButton { get; set; }
        public string DialogBoxSelect { get; set; }
        public string DialogBoxOther { get; set; }
    }
}
