//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PricingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public int rid { get; set; }
        public string Region1 { get; set; }
        public string Approver { get; set; }
        public string ApproverEmail { get; set; }
    }
}
